"use client";

import React from "react";
import type { AvatarRecipe } from "@/engine/avatar/avatar";
import { cssVars, renderAvatarSvg } from "@/engine/avatar/avatar";

export function AvatarPreview({
  recipe,
  size = 220,
}: {
  recipe: AvatarRecipe;
  size?: number;
}) {
  const vars = React.useMemo(() => cssVars(recipe), [recipe]);
  const svg = React.useMemo(() => renderAvatarSvg(recipe, size), [recipe, size]);

  return (
    <div
      style={{
        width: size,
        height: size,
        borderRadius: 18,
        border: "1px solid var(--border)",
        background: "rgba(255,255,255,0.03)",
        display: "grid",
        placeItems: "center",
        overflow: "hidden", // important for rounded corners
        ...vars, // provides --skin, --outline, etc
      }}
      // SVG is generated by our own code, not user input
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
